sonar.projectKey=pi-platform
sonar.projectName=PI Platform
sonar.sourceEncoding=UTF-8

sonar.sources=\
API_Gateway/src/main/java,\
Eureka-main/Eureka-main/src/main/java,\
payment_Microsevices/payment_Microsevices/src/main/java,\
reporting-service/src/main/java,\
esm-front-main/src

sonar.tests=\
API_Gateway/src/test/java,\
payment_Microsevices/payment_Microsevices/src/test/java,\
reporting-service/src/test/java,\
esm-front-main/src

sonar.test.inclusions=**/*Test.java,**/*Tests.java,**/*.spec.ts
sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/.angular/**,**/coverage/**,**/public/assets/**,**/*.spec.ts

sonar.java.binaries=\
API_Gateway/target/classes,\
Eureka-main/Eureka-main/target/classes,\
payment_Microsevices/payment_Microsevices/target/classes,\
reporting-service/target/classes

sonar.coverage.jacoco.xmlReportPaths=\
API_Gateway/target/site/jacoco/jacoco.xml,\
Eureka-main/Eureka-main/target/site/jacoco/jacoco.xml,\
payment_Microsevices/payment_Microsevices/target/site/jacoco/jacoco.xml,\
reporting-service/target/site/jacoco/jacoco.xml

sonar.javascript.lcov.reportPaths=\
esm-front-main/coverage/lcov.info,\
esm-front-main/coverage/edutest/lcov.info
