apiVersion: v1
kind: Service
metadata:
  name: reporting-service
  namespace: pi-platform
  labels:
    app: reporting-service
spec:
  selector:
    app: reporting-service
  ports:
    - name: http
      port: 8085
      targetPort: 8085
