apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  namespace: pi-platform
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: change-me
  SPRING_MAIL_USERNAME: replace-with-mail-user
  SPRING_MAIL_PASSWORD: replace-with-mail-app-password
