apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: pi-platform
data:
  SPRING_APPLICATION_NAME: payment-service
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pidev?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
  SPRING_DATASOURCE_USERNAME: root
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,prometheus,metrics
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
